# Generated by Django 4.0.4 on 2022-05-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Телефон'),
        ),
    ]
