# Generated by Django 4.0.4 on 2022-05-17 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('min', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Минута')),
                ('gb', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Гигабайт')),
                ('sms', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='СМС')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='MyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff', to='webapp.alltariff', verbose_name='МойТариф')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff', to=settings.AUTH_USER_MODEL, verbose_name='Абонент')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='webapp.alltariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'tariff')},
            },
        ),
    ]
