# Generated by Django 4.0.4 on 2022-05-18 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_mytariff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytariff',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='webapp.alltariff', verbose_name='МойТариф'),
        ),
        migrations.AlterField(
            model_name='mytariff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Абонент'),
        ),
        migrations.AlterUniqueTogether(
            name='mytariff',
            unique_together={('user', 'tariff')},
        ),
    ]
